### ISSUE TITLE
Safer token storage

### ISSUE THREAD

**Issue by himynameisdave** [himynameisdave/git-labelmaker#14]
See if we can lock that `token.json` file down or something, or store it as an env variable and then check it out every time?

Very least some kind of `chmod` so an malicious attack would have to sudo at least (?)

**Comment by himynameisdave** [comment]
Asked [a question on the stackoverflows](http://stackoverflow.com/questions/35283148/securely-store-data-in-a-node-cli-app)

**Comment by Jameskmonger** [comment]
Can I pick this up @himynameisdave ?

**Comment by himynameisdave** [comment]
Yes, what is your plan of action?

**Comment by Jameskmonger** [comment]
I'd like to use https://github.com/buttercup-pw/buttercup-core to encrypt the tokens. We could allow the user to choose a password which they can remember, which will be used to encrypt/decrypt the password in the buttercup archive.

**Comment by himynameisdave** [comment]
@Jameskmonger yeah I'm cool with that solution :+1:

**Comment by himynameisdave** [comment]
@Jameskmonger when you open a PR for this, please merge it into the [`v0.7.0`](https://github.com/himynameisdave/git-labelmaker/tree/v0.7.0) branch, which is my working branch for all of the [0.7.0 milestone stuff](https://github.com/himynameisdave/git-labelmaker/milestones/v0.7.0)
