### ISSUE TITLE
Allow RGB colours

### ISSUE THREAD

**Issue by Jameskmonger** [himynameisdave/git-labelmaker#21]
Rather than only accepting 3/6 digit hex colours, RGB colours could also be accepted as an input.

**Comment by himynameisdave** [comment]
Amazing, that would be super user friendly!

Okay so do you have any good snippets/modules for converting the incoming RGB values to hexes? I wrote a PostCSS plugin that does [literally the opposite](https://github.com/himynameisdave/postcss-rgb-plz) of this and will be of no help :sweat_smile:

**Comment by Jameskmonger** [comment]
@himynameisdave it's easier than it sounds!

Hex colours are also RGB values but just in hex notation. (255,255,255) and (ff,ff,ff) are the same. So you just need to convert each numeric component of the decimal RGB colour into its hexadecimal form and it will be converted! :smile:
