### ISSUE TITLE
Ability to just use predefined packages

### ISSUE THREAD

**Issue by himynameisdave** [himynameisdave/git-labelmaker#3]
There should be an option to use the awesome predefined packages inside of [`git-label-packages`](https://github.com/jasonbellamy/git-label-packages)

**Comment by Jameskmonger** [comment]
Are you accepting PRs? :smile:

**Comment by himynameisdave** [comment]
Always, what have you got in mind? :smile:

**Comment by himynameisdave** [comment]
Abandoning this. If people want to use a "well known" package like `git-label-packages` they can download it locally and then use the "Add Local Package" option.

There will be too much updating/adding/arguing over what "official" packages would be in there, which I think would be out of the scope of this project.
