### ISSUE TITLE
Add some testing

### ISSUE THREAD

**Issue by himynameisdave** [himynameisdave/git-labelmaker#30]
It's been too long that there aren't any tests for this... tsk tsk tsk :-1:

**Comment by Jameskmonger** [comment]
I think that a good solution for this would be to potentially work on a replacement project using dependency injection (so we can fully mock out all dependencies, for example `inquirer`, for full testing) which is fully test-driven and then replace the two.. what do you think?

**Comment by himynameisdave** [comment]
That sounds like a great idea, but for the scope of this issue I would just like us to have some basic tests & always write tests first as a rule of contributing

**Comment by caueops** [comment]
@himynameisdave Maybe can use [mockirer](https://github.com/ceasbz/mockirer) for mock the inquirer answers 😸

**Comment by himynameisdave** [comment]
Looks good to me, I will look into that!

...I mean it does have an emoji in the description so it must be good 👍  :P

**Comment by caueops** [comment]
Yeaah!!! If you need any help, let me know! 🙂
Em ter, 18 de out de 2016 às 21:09, Dave Lunny notifications@github.com
escreveu:

**Comment by himynameisdave** [comment]
Closed by #78 and will be released in `v0.9.0`
