### ISSUE TITLE
Display friendlier error

### ISSUE THREAD

**Issue by Jameskmonger** [himynameisdave/git-labelmaker#35]
I think we should be showing a friendlier error than the "Encrypted content has been tampered with" when the user enters the incorrect password.

**Comment by Jameskmonger** [comment]
@himynameisdave I think this should potentially be in the `0.7.3` milestone. It's quite a quick fix and would improve the tool a lot.

**Comment by himynameisdave** [comment]
@Jameskmonger Agreed

**Comment by Jameskmonger** [comment]
This was not released with `0.7.3-alpha`, and will instead be released with `0.7.3` stable which will be tomorrow.

**Comment by Jameskmonger** [comment]
This has been completed and is now awaiting review by @himynameisdave for release in `0.7.3`.
