### ISSUE TITLE
Allow resetting the token if you can't access it

### ISSUE THREAD

**Issue by Jameskmonger** [himynameisdave/git-labelmaker#38]
Allowing the user to reset their token if they can't access the archive (a forgotten password kind of feature) would mean that they can delete the archive if it exists, and creates a new one.

It would prevent any issues similar to last night! :stuck_out_tongue:

**Comment by Jameskmonger** [comment]
@himynameisdave I've applied the labels but I'm not sure which milestone you'd like this in.

**Comment by himynameisdave** [comment]
This is pretty critical but I'd also like to get `0.7.2` out asap, I'll create a `0.7.3` that we'll aim to get this out in :+1:
