### ISSUE TITLE
Password displayed in plain text

### ISSUE THREAD

**Issue by Jameskmonger** [himynameisdave/git-labelmaker#42]
When entering your password to unlock the archived token (after you've already successfully set it), the password is displayed in plain text.

**Comment by Jameskmonger** [comment]
This is an Inquirer issue.

**Comment by himynameisdave** [comment]
Just because this is an inquirer issue doesn't mean it is complete. I will lower the priority and we'll keep this open until a safer solution can be found...

**Comment by Jameskmonger** [comment]
I've noticed that the issue doesn't appear on my Ubuntu machine, it only appears (occasionally) in the Windows terminal (Node 5.6.0)

**Comment by himynameisdave** [comment]
Just tested, I don't believe it happens to me...

![screen recording 2017-04-01 at 10 59 pm](https://cloud.githubusercontent.com/assets/4298089/24584805/fbfc1834-172e-11e7-952c-ca2e4c975a48.gif)

I will check it out on Windows, and will see if resolving #77 would solve this

**Comment by himynameisdave** [comment]
I'm fairly confident that this is fixed as of 9668673f100ab2e5bfb2721220a78fe19c01df33 when the `inquirer` package was updated. Input is _always_ hidden when typing sensitive information now:

![image](https://user-images.githubusercontent.com/4298089/29000002-e9064718-7a11-11e7-8e7b-07c7baaaf892.png)

Marking this issue as closed.
