### ISSUE TITLE
Will not accept custom package file

### ISSUE THREAD

**Issue by NewAlexandria** [himynameisdave/git-labelmaker#43]
```
npm v3.6.0
node v5.6.0
```

Running `git-labelmaker`, enter my password, and choose `Add Labels From Package`.  I'm prompted for a path.  I have tried all of these (test file located at each)

```
packages/github_labels.json
github_labels.json
.github_labels.json
```

contents of file

```
[
  { "name": "ready", "color": "#159818" },
  { "name": "blocked", "color": "#e11d21" },
  { "name": "open comments", "color": "#eb6420" },
  { "name": "proposal-discussion", "color": "#84b6eb" },
  { "name": "question", "color": "#cc317c" },
  { "name": "On Hold", "color": "#666666" },
  { "name": "Revision Needed", "color": "#bfdadc" }
]
```

I hope this helps solve an issue - or improve the docs!   Thanks for your help.

**Comment by Jameskmonger** [comment]
Hi @NewAlexandria, could you try: `./github_labels.json` (in place of `github_labels.json`)?

**Comment by caseybecking** [comment]
I'm having the same issue - it keeps bouncing right back to the question for path & name of the package.

**Comment by Jameskmonger** [comment]
Thanks for raising this issue @NewAlexandria and @caseybecking.

**Comment by himynameisdave** [comment]
@Jameskmonger I wonder if they are still using a `< 0.7.2` version that doesn't include this change: https://github.com/himynameisdave/git-labelmaker/pull/37

@NewAlexandria Try and re-install this package and see if it works. Thanks for raising this issue guys, we're looking into it now!

**Comment by himynameisdave** [comment]
Not a version issue, it is actually just not accepting anything as a JSON package entry
