### ISSUE TITLE
Investigate migration from Inquirer

### ISSUE THREAD

**Issue by Jameskmonger** [himynameisdave/git-labelmaker#56]
I think Inquirer is quite heavy and has a lot of compatibility issues. We could potentially look into another solution.

**Comment by himynameisdave** [comment]
Personally, I totally disagree given that [plenty of big-name projects use it](https://www.npmjs.com/browse/depended/inquirer), including [`nodal`](https://www.npmjs.com/package/nodal) and [`nativescript`](https://www.npmjs.com/package/nativescript). Not to mention it is baked right into [Yeoman](http://yeoman.io/), a tool that is used by hundreds of developers every day.

I'm completely open to better solutions/producing our own solution, but given that `inquirer` is [regularly maintained](https://github.com/SBoudrias/Inquirer.js/releases) and, as stated, has wide adoption in the community, it would have to be a pretty good alternative.

**Comment by Jameskmonger** [comment]
I think it is a good tool, however the compatibility issues that `inquirer` suffers from on Windows make it a difficult choice fro me...

**Comment by Turbo87** [comment]
@Jameskmonger do you have an alternative?

**Comment by Jameskmonger** [comment]
No alternative @Turbo87 - I did the honourable thing a few months back and ditched Windows instead :wink:

**Comment by himynameisdave** [comment]
Closing for the same [reason mentioned here](https://github.com/himynameisdave/git-labelmaker/issues/42#issuecomment-320481058).

Again, willing to reopen if this is still an issue, but I feel like it should be fixed on Windows now.
