### ISSUE TITLE
Add a list of project using this tool

### ISSUE THREAD

**Issue by aloisdg** [himynameisdave/git-labelmaker#57]
Hello,

I think it would be a great addition to add a list of projects using this tool. It would be like a portfolio to show to someone to convince them to use it.

What do you think?

**Comment by himynameisdave** [comment]
@aloisdg I am not aware of any projects using this tool at this time (aside from me and a few of my peers). I will let you know if anyone informs me that they are using it. Meantime, [here's some folks on twitter](https://twitter.com/search?f=tweets&q=c5d2e6004b63) who may/may not be using it as they are discussing [this article](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63#.jpz6jc64u) where I discribe how to use this tool :+1:
