### ISSUE TITLE
Buttercup throwing error

### ISSUE THREAD

**Issue by himynameisdave** [himynameisdave/git-labelmaker#59]
Not sure wtf is going on, but here's a log of the error:

![screen shot 2016-03-21 at 7 46 02 pm](https://cloud.githubusercontent.com/assets/4298089/13937731/ab2a87c4-ef9d-11e5-958b-765f08c3b61c.png)

Happened when trying to run it for the first time in like a month

**Comment by himynameisdave** [comment]
Solved by deleting/re-installing my `node_modules` folder in git-labelmaker.

I don't like that. Going to try to upgrade to `buttercup@0.17.0` to see if this helps resolve any issues

**Comment by Jameskmonger** [comment]
Let me know if the 0.17.0 update fixes it. I'll log an issue with Buttercup.

**Comment by himynameisdave** [comment]
@Jameskmonger It doesn't seem to fix it

**Comment by himynameisdave** [comment]
Related: https://github.com/buttercup-pw/buttercup-core/issues/70

**Comment by himynameisdave** [comment]
Isolated incident, closing for now

**Comment by sebastienbarre** [comment]
I'm experiencing a similar issue as well. I wiped out my `node_modules`, cleaned the npm cache, and re-install `git-labelmaker` (globally), and I'm getting:

```
$ npm list -g --depth=0
/Volumes/Users/barre/.npm-packages/lib
[...]
├── git-labelmaker@0.8.0
[...]

npm ERR! extraneous: __buttercup /Volumes/Users/barre/.npm-packages/lib/node_modules/git-labelmaker/node_modules/buttercup/node_modules/__buttercup
npm ERR! error in /Volumes/Users/barre/.npm-packages/lib/node_modules/git-labelmaker/node_modules/buttercup/node_modules/__buttercup: ENOENT: no such file or directory, open '/Volumes/Users/barre/.npm-packages/lib/node_modules/git-labelmaker/node_modules/buttercup/source/package.json'
```

Thanks
