### ISSUE TITLE
Path to labels.json

### ISSUE THREAD

**Issue by TheCodeDestroyer** [himynameisdave/git-labelmaker#64]
Currently with option `Add Labels From Package` I can only take the path from current directory, it would be awesome if I could specify path to some other directory with my labels.json or even HTTP so I can use a Gist.

**Comment by Jameskmonger** [comment]
I'd be happy to pick this up @himynameisdave.

I think the best approach would be to support other local paths now, and then look at HTTP support.

**Comment by himynameisdave** [comment]
@Jameskmonger go for it!
