### ISSUE TITLE
Require sudo to store token?

### ISSUE THREAD

**Issue by jakejohns** [himynameisdave/git-labelmaker#65]
It seems that the `.git-labelmaker.bcup` is written to `/usr/local/lib/node_modules/git-labelmaker`, which means that I need to be a privileged user (`sudo git-labelmaker`) to store my token? 
eg. If i dont run with sudo first, I'm prompted for my token every time.

Would not it make more sense to use some XDG directory (data or config or something) to store the token under the users home directory? Or is intended functionality? Or am I confused about something else?

**Comment by himynameisdave** [comment]
Nope, this wasn't designed to require `sudo` to run. After some investigation, it seems that there is no need to use `sudo` if you have properly installed node/npm:

https://www.sitepoint.com/solve-global-npm-module-dependency-problem/#a-brief-note-on-security

I hope this helps, feel free to refile the issue if you are still seeing this after properly installing node. 👍
