### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by amirsobhi** [himynameisdave/git-labelmaker#75]
node -v
v6.10.1
npm -v
3.10.10
git-labelmaker 
? What is your GitHub Access Token? <redacted>
? What is your master password, to keep your access token secure? ******
TypeError: Cannot read property 'split' of undefined
    at module.exports (/usr/lib/node_modules/git-labelmaker/bin/modules/readRepo.js:14:32)
    at Promise.all.then (/usr/lib/node_modules/git-labelmaker/bin/index.js:38:19)

For now I have uninstalled git-labelmaker. It is promising though ;-)

**Comment by himynameisdave** [comment]
Thanks for submitting, sorry about the issue!

This has been fixed in https://github.com/himynameisdave/git-labelmaker/pull/66 and will be published in [`v0.9.0`](https://github.com/himynameisdave/git-labelmaker/milestone/9) which I will release today.
